#!/usr/bin/env python3
"""
Precompute full conformal triage inference + calibration pipeline.

This script runs the complete pipeline on the dataset and caches everything
to a pickle file so the Streamlit demo loads instantly without API calls:

1. Load data (synthetic or fallback to pilot)
2. Split ID data (60% cal, 40% test)
3. Run GPT-4o-mini inference (or mock) with caching
4. ConfTS: Grid search over temperatures to minimize set size
5. Apply optimal temperature
6. Conformal calibration: compute nonconformity scores and q_hat
7. Build prediction sets using APS
8. Embed all texts and fit OOD detector
9. Compute weighted CP for OOD test points
10. Save everything to data/precomputed.pkl

Usage:
    python precompute.py [--mock]

Options:
    --mock    Use MockTriageModel instead of OpenAI API (for testing without keys)
"""

import argparse
import json
import os
import pickle
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

# Fix tokenizers parallelism crash on macOS (must be set before import)
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import numpy as np
import yaml

# Add src/ to path so we can import our modules
sys.path.insert(0, str(Path(__file__).resolve().parent))

from src.model.inference import OpenAITriageModel, MockTriageModel
from src.conformal.engine import (
    TRIAGE_CLASSES,
    CLASS_TO_IDX,
    IDX_TO_CLASS,
    compute_nonconformity_scores,
    compute_qhat,
    build_prediction_sets,
)

# OOD and weighted CP require optional dependencies
try:
    from src.ood.embeddings import EmbeddingOODDetector
    from src.conformal.weighted import build_weighted_prediction_sets
    EMBEDDINGS_AVAILABLE = True
except ImportError as e:
    print(f"Warning: Optional dependencies not available: {e}")
    print("       Continuing without embeddings/weighted CP...")
    EMBEDDINGS_AVAILABLE = False
    EmbeddingOODDetector = None
    build_weighted_prediction_sets = None


def load_config() -> Dict[str, Any]:
    """Load config.yaml."""
    config_path = Path(__file__).resolve().parent / "config.yaml"
    with open(config_path) as f:
        return yaml.safe_load(f)


def load_data(config: Dict) -> Tuple[List[Dict], List[Dict]]:
    """
    Load dataset: try synthetic data first, fall back to pilot.

    Returns:
        (id_data, ood_data): list of dicts with 'id', 'symptom', 'true_label'
    """
    base_dir = Path(__file__).resolve().parent

    # Try synthetic data first
    synthetic_id = base_dir / "data" / "synthetic_triage_data.json"
    synthetic_ood = base_dir / "data" / "synthetic_triage_ood.json"

    if synthetic_id.exists() and synthetic_ood.exists():
        print("Loading synthetic data...")
        with open(synthetic_id) as f:
            id_data = json.load(f)
        with open(synthetic_ood) as f:
            ood_data = json.load(f)
        return id_data, ood_data

    # Fall back to pilot
    print("Synthetic data not found. Using pilot data...")
    pilot_id = base_dir / config["data"]["pilot_data"]
    pilot_ood = base_dir / config["data"]["pilot_ood"]

    with open(pilot_id) as f:
        id_data = json.load(f)
    with open(pilot_ood) as f:
        ood_data = json.load(f)

    print(f"Loaded {len(id_data)} ID examples and {len(ood_data)} OOD examples")
    return id_data, ood_data


def cache_logits(
    model: Any,
    id_data: List[Dict],
    cache_path: Path,
    model_name: str = "unknown",
) -> Tuple[np.ndarray, List[str], List[Dict]]:
    """
    Run inference and cache raw logits.

    Args:
        model: TriageModel instance
        id_data: List of dicts with symptom field (key may be 'symptom' or 'symptom_description')
        cache_path: Path to cache file (data/cached_logits.json)
        model_name: Model identifier for cache validation

    Returns:
        (raw_logits, predictions, results_for_cache)
    """
    # Check for existing cache
    if cache_path.exists():
        print(f"Loading cached logits from {cache_path}...")
        with open(cache_path) as f:
            cached = json.load(f)

        # Validate cache: check size matches, and model matches
        cache_meta = cached[0].get("_model", "") if cached else ""
        cache_n = len(cached) if not cache_meta else len([c for c in cached if "raw_logits" in c])

        if cache_n != len(id_data):
            print(f"  WARNING: Cache has {cache_n} entries but data has {len(id_data)}. Invalidating cache.")
        elif model_name == "mock" and cache_meta != "mock":
            # Allow mock cache only if we're in mock mode
            print(f"  WARNING: Cache was not generated by mock model. Invalidating cache.")
        elif model_name != "mock" and cache_meta == "mock":
            print(f"  WARNING: Cache was generated by mock model but we need real API logits. Invalidating cache.")
        else:
            # Cache is valid
            raw_logits = np.array([r["raw_logits"] for r in cached if "raw_logits" in r])
            predictions = np.array([r["predicted_class"] for r in cached if "predicted_class" in r])
            if len(raw_logits) == len(id_data):
                print(f"  Cache valid: {len(raw_logits)} entries, model={cache_meta or 'unknown'}")
                return raw_logits, predictions, cached
            else:
                print(f"  WARNING: Cache entry count mismatch after filtering. Invalidating.")

    print(f"Running inference on {len(id_data)} examples (this may take a while)...")
    results = []

    for i, item in enumerate(id_data):
        if i > 0 and i % 50 == 0:
            print(f"  Processed {i}/{len(id_data)} examples...")

        # Support both 'symptom' and 'symptom_description' keys
        symptom = item.get("symptom_description", item.get("symptom", ""))
        result = model.predict(symptom)

        # Store for caching
        results.append({
            "id": item.get("id", i),
            "predicted_class": result["predicted_class"],
            "raw_logits": result["raw_logits"].tolist(),
            "raw_response": result.get("raw_response", ""),
            "_model": model_name,
        })

    # Save to cache
    print(f"Caching {len(results)} logits to {cache_path}...")
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    with open(cache_path, "w") as f:
        json.dump(results, f, indent=2)

    raw_logits = np.array([r["raw_logits"] for r in results])
    predictions = np.array([r["predicted_class"] for r in results])

    return raw_logits, predictions, results


def confts_grid_search(
    raw_logits: np.ndarray,
    true_labels: np.ndarray,
    cal_indices: np.ndarray,
    alpha: float = 0.10,
) -> Tuple[float, List[Dict]]:
    """
    Find optimal temperature T via grid search using THRESHOLD method.

    IMPORTANT: We use the threshold method (not APS) because GPT-4o-mini
    produces sparse logprobs: one class near 0, others at -20.0. After softmax,
    this gives one class at ~95%+ and others at ~0%. APS always produces
    exactly size-2 sets with such distributions because:
    - First class contributes nonconformity ~0 (not enough)
    - Second class contributes ~1 (immediately exceeds q_hat)
    The threshold method checks each class independently (P(y) >= 1-q_hat),
    giving singletons for confident predictions and larger sets for uncertain ones.

    Returns:
        (optimal_T, search_results)
    """
    print("Running ConfTS grid search (threshold method)...")

    # Split calibration into two parts: for temp search and for validation
    n_cal = len(cal_indices)
    rng = np.random.RandomState(42)
    perm = rng.permutation(n_cal)
    n_search = int(0.5 * n_cal)
    search_indices = cal_indices[perm[:n_search]]
    val_indices = cal_indices[perm[n_search:]]

    temperatures = [0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 3.0, 5.0]
    search_results = []
    best_T = 1.0
    best_set_size = 4.0

    for T in temperatures:
        # Apply temperature scaling
        search_probs = np.array([
            OpenAITriageModel.apply_temperature_scaling(logits, T)
            for logits in raw_logits[search_indices]
        ])
        search_labels = true_labels[search_indices]

        # Compute nonconformity scores and q_hat
        search_scores = compute_nonconformity_scores(search_probs, search_labels)
        q_hat = compute_qhat(search_scores, alpha=alpha)
        threshold = 1.0 - q_hat

        # Evaluate on validation split using THRESHOLD method
        val_probs = np.array([
            OpenAITriageModel.apply_temperature_scaling(logits, T)
            for logits in raw_logits[val_indices]
        ])
        val_labels = true_labels[val_indices]

        # Build prediction sets with threshold method
        sizes = []
        covered = 0
        for i in range(len(val_indices)):
            pred_set = [j for j in range(4) if val_probs[i, j] >= threshold]
            if not pred_set:
                pred_set = [int(np.argmax(val_probs[i]))]
            sizes.append(len(pred_set))
            if val_labels[i] in pred_set:
                covered += 1

        coverage = covered / len(val_indices) if len(val_indices) > 0 else 0.0
        avg_set_size = float(np.mean(sizes)) if sizes else 0.0

        search_results.append({
            "T": T,
            "coverage": coverage,
            "avg_set_size": avg_set_size,
            "q_hat": float(q_hat),
        })

        print(f"  T={T:.2f}: coverage={coverage:.3f}, avg_set_size={avg_set_size:.3f}, q_hat={q_hat:.4f}")

        # Pick T that minimizes set size subject to coverage >= 1-alpha
        if coverage >= (1 - alpha):
            if avg_set_size < best_set_size:
                best_set_size = avg_set_size
                best_T = T

    # If no T met coverage on the nested split, pick T with best coverage
    if all(r["coverage"] < (1 - alpha) for r in search_results):
        # Coverage is borderline (conformal guarantee is in expectation, finite
        # sample fluctuations are normal). Pick T with coverage closest to target.
        best_r = max(search_results, key=lambda r: r["coverage"])
        best_T = best_r["T"]
        best_set_size = best_r["avg_set_size"]
        print(f"  NOTE: No T achieved coverage >= {1-alpha:.2f} on nested split.")
        print(f"  This is normal with finite data — conformal coverage is an expected guarantee.")
        print(f"  Picking T={best_T} with highest coverage ({best_r['coverage']:.3f}).")

    print(f"Optimal T: {best_T} (avg_set_size={best_set_size:.3f})")

    return best_T, search_results


def compute_embeddings(
    detector: EmbeddingOODDetector,
    id_data: List[Dict],
    ood_data: List[Dict],
    cal_indices: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Embed all texts and compute k-NN distances.

    Returns:
        (embeddings_id, embeddings_ood, knn_cal, knn_test, knn_ood)
    """
    print("Computing embeddings...")

    # Extract texts (support multiple field names)
    id_texts = [item.get("symptom_description", item.get("symptom", "")) for item in id_data]
    ood_texts = [item.get("symptom_description", item.get("symptom", "")) for item in ood_data]
    cal_texts = [id_texts[i] for i in cal_indices]

    # Embed everything
    embeddings_id = detector.embed(id_texts)
    embeddings_ood = detector.embed(ood_texts)

    print(f"  ID embeddings: shape {embeddings_id.shape}")
    print(f"  OOD embeddings: shape {embeddings_ood.shape}")

    # Fit k-NN on calibration set
    detector.fit_calibration(cal_texts)

    # Compute distances
    knn_cal = detector.compute_calibration_distances()  # LOO distances
    knn_test = detector.compute_distances(
        [id_texts[i] for i in range(len(id_texts)) if i not in cal_indices]
    )
    knn_ood = detector.compute_distances(ood_texts)

    print(f"  Calibration distances: mean={np.mean(knn_cal):.4f}, std={np.std(knn_cal):.4f}")
    print(f"  Test distances: mean={np.mean(knn_test):.4f}, std={np.std(knn_test):.4f}")
    print(f"  OOD distances: mean={np.mean(knn_ood):.4f}, std={np.std(knn_ood):.4f}")

    return embeddings_id, embeddings_ood, knn_cal, knn_test, knn_ood


def main(mock: bool = False, skip_embeddings: bool = False):
    """Run full precompute pipeline."""
    print("="*70)
    print("Conformal Triage Demo — Precompute Pipeline")
    print("="*70)

    # Load config
    config = load_config()
    alpha = config["conformal"]["alpha"]
    cal_ratio = config["conformal"]["cal_ratio"]
    random_seed = config["conformal"]["random_seed"]
    embedding_model = config["ood"]["embedding_model"]
    k_neighbors = config["ood"]["k_neighbors"]
    beta = config["ood"]["beta"]

    # Create output directory
    output_dir = Path(__file__).resolve().parent / "data"
    output_dir.mkdir(parents=True, exist_ok=True)
    cache_path = output_dir / "cached_logits.json"
    output_pkl = output_dir / "precomputed.pkl"
    output_json = output_dir / "precompute_summary.json"

    # Load data
    print("\n[1/11] Loading data...")
    id_data, ood_data = load_data(config)
    n_id = len(id_data)
    n_ood = len(ood_data)
    print(f"  ID: {n_id} examples, OOD: {n_ood} examples")

    # Split ID data
    print("\n[2/11] Splitting ID data (60% cal, 40% test)...")
    rng = np.random.RandomState(random_seed)
    indices = rng.permutation(n_id)
    n_cal = int(np.ceil(n_id * cal_ratio))
    cal_indices = indices[:n_cal]
    test_indices = indices[n_cal:]
    print(f"  Calibration: {len(cal_indices)}, Test: {len(test_indices)}")

    # Extract labels (support both 'true_label' and 'triage_level')
    true_labels = np.array([
        CLASS_TO_IDX[item.get("triage_level", item.get("true_label", "gp_visit"))]
        for item in id_data
    ])

    # Initialize model
    print("\n[3/11] Initializing model...")
    if mock:
        print("  Using MockTriageModel (no API key needed)")
        model = MockTriageModel(seed=random_seed)
    else:
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key and not cache_path.exists():
            print("ERROR: OPENAI_API_KEY not set and no cached logits found!")
            print("Set OPENAI_API_KEY or use --mock flag.")
            sys.exit(1)
        model = OpenAITriageModel(
            api_key=api_key,
            model=config["model"]["api_model"],
            temperature=config["model"]["temperature"],
        )

    # Run inference with caching
    print("\n[4/11] Running inference and caching logits...")
    model_name = "mock" if mock else config["model"]["api_model"]
    raw_logits, predictions, cached_results = cache_logits(model, id_data, cache_path, model_name=model_name)
    print(f"  Raw logits shape: {raw_logits.shape}")

    # ConfTS grid search
    print("\n[5/11] ConfTS grid search...")
    optimal_T, confts_results = confts_grid_search(
        raw_logits, true_labels, cal_indices, alpha=alpha
    )

    # Apply optimal temperature
    print("\n[6/11] Applying optimal temperature scaling...")
    calibrated_probs = np.array([
        OpenAITriageModel.apply_temperature_scaling(logits, optimal_T)
        for logits in raw_logits
    ])
    print(f"  Calibrated probs shape: {calibrated_probs.shape}")
    print(f"  Sample prob for first example: {calibrated_probs[0]}")

    # Conformal calibration on full calibration set
    print("\n[7/11] Conformal calibration...")
    cal_probs = calibrated_probs[cal_indices]
    cal_labels = true_labels[cal_indices]
    cal_scores = compute_nonconformity_scores(cal_probs, cal_labels)
    q_hat = compute_qhat(cal_scores, alpha=alpha)
    print(f"  q_hat: {q_hat:.4f}")
    print(f"  Nonconformity scores: min={np.min(cal_scores):.4f}, max={np.max(cal_scores):.4f}, mean={np.mean(cal_scores):.4f}")

    # Build prediction sets for test split using THRESHOLD method
    # (not APS — see confts_grid_search docstring for why)
    print("\n[8/11] Building prediction sets (test split, threshold method)...")
    test_probs = calibrated_probs[test_indices]
    test_labels = true_labels[test_indices]
    test_df = build_prediction_sets(
        test_probs, q_hat, test_labels, method="threshold"
    )
    coverage = float(test_df["contains_true"].mean())
    avg_set_size = float(test_df["set_size"].mean())
    accuracy = float(test_df["is_correct"].mean())
    print(f"  Coverage: {coverage:.3f} (target >= {1-alpha:.3f})")
    print(f"  Avg set size: {avg_set_size:.3f}")
    print(f"  Accuracy: {accuracy:.3f}")

    # Compute set size distribution
    set_size_dist = {}
    for size in range(1, 5):
        count = (test_df["set_size"] == size).sum()
        set_size_dist[size] = int(count)
    print(f"  Set size distribution: {set_size_dist}")
    singleton_pct = 100 * set_size_dist.get(1, 0) / len(test_df)
    print(f"  Singleton rate: {singleton_pct:.1f}%")

    # Embeddings and OOD detection
    if skip_embeddings:
        EMBEDDINGS_AVAILABLE_NOW = False
        print("\n[9/11] Skipping embeddings (--skip-embeddings flag)")
    else:
        EMBEDDINGS_AVAILABLE_NOW = EMBEDDINGS_AVAILABLE

    if EMBEDDINGS_AVAILABLE_NOW:
        print("\n[9/11] Computing embeddings...")
        print("  (If this segfaults, re-run with --skip-embeddings, then fix with:")
        print("   pip install tokenizers --upgrade && pip install sentence-transformers --upgrade)")
        sys.stdout.flush()
        detector = EmbeddingOODDetector(model_name=embedding_model, k=k_neighbors)
        embeddings_id, embeddings_ood, knn_cal, knn_test, knn_ood = compute_embeddings(
            detector, id_data, ood_data, cal_indices
        )

        # OOD AUC
        print("\n[10/11] Evaluating OOD separation...")
        id_texts = [item.get("symptom_description", item.get("symptom", "")) for item in id_data]
        ood_texts = [item.get("symptom_description", item.get("symptom", "")) for item in ood_data]
        ood_eval = detector.evaluate_ood_separation(id_texts, ood_texts)
        print(f"  OOD AUC: {ood_eval['auc']:.3f}")
        print(f"  Mean ID distance: {ood_eval['mean_id_distance']:.4f}")
        print(f"  Mean OOD distance: {ood_eval['mean_ood_distance']:.4f}")

        # Weighted CP on test split
        print("\n[11/11] Building weighted CP prediction sets...")
        weighted_results = build_weighted_prediction_sets(
            test_probs, cal_scores, knn_cal, knn_test, alpha=alpha, beta=beta
        )
        weighted_sizes = np.array([r["set_size"] for r in weighted_results])
        print(f"  Weighted CP avg set size: {np.mean(weighted_sizes):.3f}")
        print(f"  Size increase vs standard CP: {np.mean(weighted_sizes) - avg_set_size:.3f}")
    if not EMBEDDINGS_AVAILABLE_NOW:
        if skip_embeddings:
            print("\n[9/11] Skipped (--skip-embeddings)")
        else:
            print("\n[9/11] Skipping embeddings (dependencies not available)")
        print("\n[10/11] Skipping OOD evaluation")
        print("\n[11/11] Skipping weighted CP")
        embeddings_id = np.zeros((len(id_data), 384))
        embeddings_ood = np.zeros((len(ood_data), 384))
        knn_cal = np.zeros(len(cal_indices))
        knn_test = np.zeros(len(test_indices))
        knn_ood = np.zeros(len(ood_data))
        ood_eval = {"auc": 0.0, "mean_id_distance": 0.0, "mean_ood_distance": 0.0}
        weighted_results = []
        weighted_sizes = np.array([])  # Empty array for summary

    # Build prediction sets for all data (for visualization)
    print("\nBuilding full prediction sets (all ID data, threshold method)...")
    all_pred_sets = []
    for i in range(len(id_data)):
        probs = calibrated_probs[i]
        pred_set = build_prediction_sets(
            probs.reshape(1, -1), q_hat, method="threshold"
        ).iloc[0]
        all_pred_sets.append({
            "id": i,
            "prediction_set": frozenset(pred_set["prediction_set"]),
            "set_size": pred_set["set_size"],
            "max_prob": pred_set["max_prob"],
        })

    # Prepare output dictionary
    print("\nPackaging results...")
    precomputed = {
        "config": {
            "alpha": alpha,
            "optimal_T": float(optimal_T),
            "q_hat": float(q_hat),
            "cal_ratio": cal_ratio,
            "random_seed": random_seed,
            "model": "mock" if mock else config["model"]["api_model"],
            "embedding_model": embedding_model,
            "prediction_method": "threshold",  # not APS — sparse logprobs need threshold
            "n_id": n_id,
            "n_ood": n_ood,
            "n_cal": int(len(cal_indices)),
            "n_test": int(len(test_indices)),
        },
        "id_data": id_data,
        "ood_data": ood_data,
        "raw_logits": raw_logits,
        "calibrated_probs": calibrated_probs,
        "predictions": predictions,
        "true_labels": true_labels.tolist(),
        "cal_indices": cal_indices,
        "test_indices": test_indices,
        "cal_scores": cal_scores,
        "q_hat": float(q_hat),
        "prediction_sets": all_pred_sets,
        "embeddings_id": embeddings_id,
        "embeddings_ood": embeddings_ood,
        "knn_distances_cal": knn_cal,
        "knn_distances_test": knn_test,
        "knn_distances_ood": knn_ood,
        "ood_auc": ood_eval["auc"],
        "confts_search_results": confts_results,
        "weighted_cp_results": weighted_results,
        "set_size_distribution": set_size_dist,
        "coverage": coverage,
        "accuracy": accuracy,
    }

    # Save pickle
    print(f"\nSaving to {output_pkl}...")
    with open(output_pkl, "wb") as f:
        pickle.dump(precomputed, f, protocol=pickle.HIGHEST_PROTOCOL)
    print(f"  Done. File size: {output_pkl.stat().st_size / 1024 / 1024:.1f} MB")

    # Save human-readable summary
    print(f"\nSaving summary to {output_json}...")
    summary = {
        "config": precomputed["config"],
        "n_examples": n_id,
        "coverage": coverage,
        "accuracy": accuracy,
        "avg_set_size": avg_set_size,
        "set_size_distribution": set_size_dist,
        "ood_auc": ood_eval["auc"],
        "confts_optimal_T": float(optimal_T),
        "confts_search_results": confts_results,
        "weighted_cp_avg_size_increase": float(np.mean(weighted_sizes) - avg_set_size) if len(weighted_sizes) > 0 else 0.0,
    }
    with open(output_json, "w") as f:
        json.dump(summary, f, indent=2)

    print("\n" + "="*70)
    print("Precompute complete!")
    print(f"  Pickle: {output_pkl}")
    print(f"  Summary: {output_json}")
    print("="*70)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Precompute conformal triage pipeline")
    parser.add_argument(
        "--mock",
        action="store_true",
        help="Use MockTriageModel instead of OpenAI API"
    )
    parser.add_argument(
        "--skip-embeddings",
        action="store_true",
        help="Skip embedding computation (use if sentence-transformers segfaults)"
    )
    args = parser.parse_args()

    main(mock=args.mock, skip_embeddings=args.skip_embeddings)
